### PR TITLE
Workspace refactoring

### PR DESCRIPTION
**Pull request by ubruhin**
The purpose of this pull request is to implement the new workspace/library/repository concept which is discussed in #109. Just started, not yet ready to merge...

### CODE REVIEW

**Comment by ubruhin** [comment]
I think this should be (more or less) ready to merge.

### The workspace directory structure looks now like this:
```
workspace/
    ├── .librepcb-workspace
    ├── projects/
    │   ├── Project_A/
    │   ├── Project_B/
    │   └── Project_C/
    ├── v0.1/
    │   ├── metadata/
    │   └── libraries/
    │       ├── local/
    │       │   ├── Library_A.lplib/
    │       │   ├── Library_B.lplib/
    │       │   └── Library_C.lplib/
    │       └── remote/
    │           ├── 5d9abd1b-cf0b-4cf7-8666-20a1add9971e.lplib/
    │           ├── 193ef70d-8dab-4a6c-a672-274c5bf09b68.lplib/
    │           └── c2c427a9-17c6-4400-981c-6ece1c9735c3.lplib/
    ├── v0.2/
    │   ├── metadata/
    │   └── libraries/
    │       ├── local/
    │       │   ├── Library_A.lplib/
    │       │   ├── Library_B.lplib/
    │       │   └── Library_C.lplib/
    │       └── remote/
    │           ├── 5d9abd1b-cf0b-4cf7-8666-20a1add9971e.lplib/
    │           ├── 193ef70d-8dab-4a6c-a672-274c5bf09b68.lplib/
    │           └── c2c427a9-17c6-4400-981c-6ece1c9735c3.lplib/
    └── v1/
        ├── metadata/
        └── libraries/
            ├── local/
            │   ├── Library_A.lplib/
            │   ├── Library_B.lplib/
            │   └── Library_C.lplib/
            └── remote/
                ├── 5d9abd1b-cf0b-4cf7-8666-20a1add9971e.lplib/
                ├── 193ef70d-8dab-4a6c-a672-274c5bf09b68.lplib/
                └── c2c427a9-17c6-4400-981c-6ece1c9735c3.lplib/
```

### A library directory structure looks like this:
```
My_Library.lplib/
├── .librepcb-lib
├── icon.png
├── library.xml
├── cmp/
│   └── 09febfc6-fb2d-4739-ac57-51ac56a01e7d/
│       ├── component.xml
│       └── .librepcb-cmp
├── cmpcat/
│   └── 09febfc6-fb2d-4739-ac57-51ac56a01e7d/
│       ├── component_category.xml
│       └── .librepcb-cmpcat
├── dev/
│   └── 09febfc6-fb2d-4739-ac57-51ac56a01e7d/
│       ├── device.xml
│       └── .librepcb-dev
├── pkg/
│   └── 09febfc6-fb2d-4739-ac57-51ac56a01e7d/
│       ├── package.xml
│       └── .librepcb-pkg
├── pkgcat/
│   └── 09febfc6-fb2d-4739-ac57-51ac56a01e7d/
│       ├── package_category.xml
│       └── .librepcb-pkgcat
└── sym/
    └── 09febfc6-fb2d-4739-ac57-51ac56a01e7d/
        ├── symbol.xml
        └── .librepcb-sym
```

### A project directory structure looks like this:
```
My_Project/
├── .librepcb-project
├── My_Project.lpp
├── README.md
├── boards/
│   ├── my_board_1.xml
│   └── my_board_2.xml
├── core/
│   ├── circuit.xml
│   ├── erc.xml
│   └── settings.xml
├── library/
│   └── same subdirectories like a library (cmp, dev, pkg, sym)
├── output/
│   └── v1/
│       ├── My_Project_Schematics.pdf
│       └── gerber/
│           └── *.gbr
└── schematics/
    ├── my_sheet_1.xml
    └── my_sheet_2.xml
```

**Comment by ubruhin** [comment]
Here you can see two new features in the control panel:

 - 1) The warning which is shown when the workspace was already used with a newer application version and is then used with an older version again.
 - 2) The progress of the library scanner (which runs now asynchronously in a separate thread, so the application can be used while the library gets scanned).

control panel - librepcb 0 1_007

**Comment by dns2utf8** [comment]
Is it too late? I think .librepcb-lib and library.xml are redundant.

The same goes for .librepcb-project and My_Project.lpp

I think the visible one would be best, maybe change the name of library.xml to My-Library.lplib.
Pros: User can (double) click it

**Comment by dns2utf8** [comment]
Is it too late? I think .librepcb-lib and library.xml are redundant.

The same goes for .librepcb-project and My_Project.lpp

I think the visible one would be best, maybe change the name of library.xml to My-Library.lplib.
Pros: User can (double) click it

**Comment by dbrgn** [comment]
> I think the visible one would be best, maybe change the name of library.xml to My-Library.lplib. Pros: User can (double) click it.

I don't think that libraries can be opened standalone. That's what `My_Project.lpp` is for.

> A library directory structure looks like this:
>
> > My_Library.lplib/

Didn't we want to get rid of the `.lplib` suffix of the library directory?

**Comment by ubruhin** [comment]
> Is it too late? I think .librepcb-lib and library.xml are redundant.
> The same goes for .librepcb-project and My_Project.lpp

The purpose of the hidden files is to indicate whether a directory contains a library or a project, and in which file format version (the content of these files are for example "0.1" which is the current file format version). These files will be forward compatible, so an old application version will still recognize libraries/projects which were created with a newer application version. When trying to open such a library/project, a message box shows an error like "You need at least LibrePCB version x.y to open this library/project".

All other files in the directories are **not** forward compatible, so the file `library.xml` may be renamed to `awesome_library.json` someday, and later to `foo.bar` maybe ;)


>> I think the visible one would be best, maybe change the name of library.xml to My-Library.lplib. Pros: User can (double) click it.

> I don't think that libraries can be opened standalone. That's what My_Project.lpp is for.

*Project libraries* would not make sense to be opened standalone, but they even don't have a `*.library.xml` file. *Workspace libraries* would maybe make sense to be opened standalone, but at the moment I don't see that this is really required... I think it's enough to let users open a library from within the application. But thanks to `.librapcb-lib` we are free to change this behavior in future :)

> Didn't we want to get rid of the .lplib suffix of the library directory?

It was just an idea, but I didn't liked it very much. I like to easily recognize libraries by their directory suffix (e.g. on GitHub). And @rnestler didn't have a real opinion about that ;)

**Comment by dbrgn** [comment]
> It was just an idea, but I didn't like it very much. I like to easily recognize libraries by their directory suffix (e.g. on GitHub). And @rnestler didn't have a real opinion about that ;)

Can we name them like that as a default, but without enforcing it?

**Comment by ubruhin** [comment]
> Can we name them like that as a default, but without enforcing it?

No. :laughing:
I think it would confuse users when libraries sometimes have the suffix, and sometimes not...

**Comment by dbrgn** [comment]
@The-Compiler what do you think about the requirement of naming library directories / repositories with ".lplib"?

**Comment by The-Compiler** [comment]
No strong opinion here - it's a bit weird to enforce an "extension" for a directory, but I see how it makes sense.

**Comment by ubruhin** [comment]
I would say for the beginning we enforce the ".lplib" extension. When the user base gets larger and many users also don't like the suffix, we are free to remove this enforcement. This would not break any library, so the transition could be done step by step. The other way (introducing the suffix enforcement) would be much harder as this breaks all existing libraries.

**Comment by dbrgn** [comment]
Ok, let's do that.

**Pull request merged**
