### PR TITLE
Library Editor: Make "Close Library Editor" menu item working

### LINKED ISSUE #297: Library Editor: "Close Library Editor" Menu Item has no effect
##### LibrePCB VERSION

7acdba9af0cdf3bf03d957a04dffda7966bfb33d

##### OS / ENVIRONMENT

Arch Linux

##### SUMMARY

Clicking the "Close Library Editor" menu item in Library Editor has no effect.

##### STEPS TO REPRODUCE

Click menu item.

##### EXPECTED RESULTS

Library Editor should close.

##### ACTUAL RESULTS

Library Editor does not close.

### PR DESCRIPTION
**Pull request by 0xB767B**
Fixes #297

### CODE REVIEW

**Comment by ubruhin** [comment]
Thx :)

The `closeTriggered()` function is not needed, you can connect the signal directly to the slot `LibraryEditor::close` (which is inherited from `QWidget`).

And could you please rebase the branch to master?

**Comment by 0xB767B** [comment]
I thought it would make sense to call ```closeAndDestroy``` so that saving is handled?

Wasn't the request already rebased?

**Comment by ubruhin** [comment]
> I thought it would make sense to call closeAndDestroy so that saving is handled?

There's an event handler for the close event which should call closeAndDestroy anyway, so no need to do it manually (clicking on the "X" in the title bar also just calls `close()`).

**Comment by ubruhin** [comment]
Thanks! :+1:

**Pull request merged**
