### PR TITLE
Refactor serialization

### PR DESCRIPTION
**Pull request by ubruhin**
The concept of serialization was inconsistent until now:
- To deserialize elements, the XML element tag names were defined outside the classes to be deserialized (e.g. the string "pin" was defined in the `SymbolPin`'s outer class `Symbol`).
- To serialize elements, the classes to be serialized defined their XML element tag names in their own function `serializeToXmlDomElement()` (e.g. the string "pin" was defined in the class `SymbolPin`).

So nearly every XML tag name was defined in two different classes. To make this more consistent, XML tag names are now always defined in the outer classes (as described in the first point above) and are passed to the inner classes as argument of `serializeToXmlDomElement()`. This way it is also possible to use different XML tag names for the same class, for example if a common/generic class is used in very different contexts.

Other changes:
- Replace the interface `IF_XmlSerializableObject` with the new class `SerializableObject`.
- Make `serializeToXmlDomElement()` no longer pure virtual and implement it in `SerializableObject` instead. From now on this is only a convenience method.
- Add the pure virtual method `serialize(XmlDomElement& root)`. In contrast to `serializeToXmlDomElement()` this new method allows to serialize multiple objects into the same DOM element (this is useful in some cases, e.g. to serialize a list of objects of mixed types).
- Remove `checkAttributesValidity()` because it was bad design (see #157).

### CODE REVIEW

**Comment by dbrgn** [comment]
I can't judge the code, but from your description, it sounds good. And if more code is removed than added, then it *must* be good :wink:

**Comment by ubruhin** [comment]
> And if more code is removed than added, then it must be good

Absolutely! :smile: 

But now I have added the new class template [`SerializableObjectList`](https://github.com/LibrePCB/LibrePCB/blob/refactor_serialization/libs/librepcb/common/fileio/serializableobjectlist.h) :wink:  This class is still work-in-progress, and my idea is to add even more such classes (see commit message of 18cbb6c1945d07fee0664ba1a0e05288637aca48).

At the moment, these classes increase the total LOC, but if they are widely used in future, the total LOC will be reduced for sure. But I'm still not sure if these classes can be designed generic enough to make them usable enough...

@dbrgn @rnestler Any thoughts on my first draft of [`SerializableObjectList`](https://github.com/LibrePCB/LibrePCB/blob/refactor_serialization/libs/librepcb/common/fileio/serializableobjectlist.h)?

**Comment by ubruhin** [comment]
Unfortunately I was not as successful as hoped for with the new template class `SerializableObjectList`, so I decided to remove it again :unamused: 

Instead, I added some helper functions to easily serialize whole containers: https://github.com/LibrePCB/LibrePCB/blob/refactor_serialization/libs/librepcb/common/fileio/serializableobject.h#L88-L122

Now the overall balance between added and removed lines of code is even better :smiley:

**Comment by ubruhin** [comment]
Ok the class `SerializableObjectList` is there again :see_no_evil: Now it seems that it works quite good (it is heavily used on the branch `add_library_editor`)....

**Pull request merged**
