### PR TITLE
Support Qt 5.10

### PR DESCRIPTION
**Pull request by NZSmartie**
See #230

### CODE REVIEW

**Comment by NZSmartie** [comment]
So, the PPA that provides up to date builds for Qt Toolchain only provides Qt 5.10 for Ubuntu Xenial (16.04) https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.10.0-xenial. 

However, Travis CI do not provide a build environment for Xenial because of maintenance costs. https://github.com/travis-ci/travis-ci/issues/5821

`.travis.yml` has a build matrix setup for multiple Qt builds, but I wont be able to add one for Qt 5.10

**Comment by NZSmartie** [comment]
Atleast Qt 5.9 is available for Trusty and already part of travis-ci builds. AppVeyor was at 5.7 which I had bumped that up to 5.10 but could bump it back down to 5.9 to keep the version numbers consistent across platform builds. 
That way if a bug occurs or there's a API issue, we can rule out Qt being different for different platforms

**Comment by ubruhin** [comment]
Great, thanks! Looks good for me, but it seems that on AppVeyor the test `QLiteDatabaseTest.testConcurrentAccessFromMultipleThreads` now takes massively longer (~14s instead of ~10s) and thus the test fails. I retriggered the build to see if it fails again...

**Comment by ubruhin** [comment]
OK, now with Qt 5.9.3 it works also on AppVeyor :+1:

**Pull request merged**
