### PR TITLE
Add schematic editor activity diagrams

### PR DESCRIPTION
**Pull request by ubruhin**
@0xB767B Is this the type of diagram you want to have?

diagram

### CODE REVIEW

**Comment by 0xB767B** [comment]
Yes, that's what I had in mind. But I would avoid having "and" in a block but rather use two blocks. It makes the distinct steps better visible. Furthermore it helps structuring the diagram better.

**Comment by ubruhin** [comment]
> But I would avoid having "and" in a block but rather use two blocks.

Ack! I have updated the diagram accordingly.

**Comment by 0xB767B** [comment]
Thumbs up!

These activity diagrams build a great foundation for detailed description for activity/flow in tools. Nevertheless I think we cannot avoid having an overall/general specification of the user interface. E.g. your magic right-click ;-) This might be expressed in activity diagrams as well. Or maybe just in pure prose ;-)

**Comment by 0xB767B** [comment]
Btw: Title of issue is missleading. We are talking about deinition of workflow/usage. FSM is a implementatio detail.

**Comment by ubruhin** [comment]
> Title of issue is missleading

fixed.

**Comment by ubruhin** [comment]
Now there is also an activity overview diagram/description. Hope this helps...

diagram

**Comment by ubruhin** [comment]
Added new diagram:

diagram

**Pull request merged**
