### PR TITLE
Improve UI/UX

### PR DESCRIPTION
**Pull request by 5n8ke**
# Unify User Interface
This PR improves the UI/UX by unifying the interface of the control panel and editors.

## Refactor ControlPanel
- Update Mnemonics
- Add Keyboard Shortcuts
- Unify context menu and use helper functions
- [ ] Open project with Enter key from the file list

## Other Changes
- Add Ctrl+F Shortcut to focus on the search toolbar
- [x] Change search behavior (#756 )
- [x] Improve context menu and item selection of editors (#757 )
- [ ] Reuse code for via/pad shape selection (#759) 

## Todo
- [x] Rename short fsm file names to long versions (like BES_* -> BoardEditorState_*)
- [ ] Create reusable menus (e.g. always the same help menu)
- [ ] Create a consistent, globally available shortcut manager and editor
  - [ ] Investigate impact single letter key shortcuts (e.g R for rotate)
  - [ ] Add keyboard shortcuts to librarymanager
  - [ ] Compile list of keyboard shortcuts
  - [ ] Add more keyboard shortcuts to libraryeditor

### CODE REVIEW

**Comment by ubruhin** [comment]
Ah, btw:

> Rename long fsm file names to short versions (like BoardEditorState_* -> BES_*)

Actually I'd like to do the opposite: Renaming BES_ to BoardEditorState_ :grin: Just a few weeks ago I renamed SES_ to SchematicEditorState_ in #720 to make the names much more expressive...

**Comment by 5n8ke** [comment]
> Actually I'd like to do the opposite: Renaming BES_ to BoardEditorState_ :grin: Just a few weeks ago I renamed SES_ to SchematicEditorState_ in #720 to make the names much more expressive...

As long as it's consistent. Personally I prefer the short version, since all other groups of classes also use abbreviations (BI_Base,...)

**Comment by dbrgn** [comment]
As someone that only works on the code occasionally, I'd appreciate the longer form of the names :slightly_smiling_face:

**Comment by ubruhin** [comment]
Since this PR is now in draft state for a long time without any updates, and most (or even all?) of the changes have been implemented already in the mean time, I'll close this. If there are still some changes relevant, please let me know. Thanks, and sorry for the obsolete effort!

**Pull request closed without merging**
