### PR TITLE
Length: Implement mmStringToNm() to use only integer operations

### PR DESCRIPTION
**Pull request by eduardosm**
If tests should be extended or there are some style issues, or anything else, please, say so.

### CODE REVIEW

**Comment by ubruhin** [comment]
Awesome! :smiley: 

That's a lot of code xD Did you write it completely by yourself or is it copied from somewhere?

I couldn't yet review it in detail (will do that soon), just two things I noticed already:
- Test class `UnitsLengthTest` should be named only `LengthTest`
- Generally it would be better to write only one (or a few) `EXPECT_*()` statements per test function, and supply the function with different test data. See for example `PointTest::testRotate()`. It's not tragic, I would also merge it the way it is now :)

**Comment by ubruhin** [comment]
> I wrote all myself grinning but its not the first time I wrote similar code to parse numbers.

OK, I see :)

> Done, I also moved the test to the parent (common) directory, because pointtest.cpp was there.

:+1:

> I took a look at it, but I'm not sure how to pass different test data to EXPECT_EQ and EXPECT_THROW, unless I create two different test classes.

I've found a test which does exactly the same thing: 

https://github.com/LibrePCB/LibrePCB/blob/35af6dc8d323821b1f9c7d17551e701c45434eee/tests/unittests/common/uuidtest.cpp#L161-L168

**Comment by eduardosm** [comment]
> I've found a test which does exactly the same thing:
> 
> [LibrePCB/tests/unittests/common/uuidtest.cpp](https://github.com/LibrePCB/LibrePCB/blob/35af6dc8d323821b1f9c7d17551e701c45434eee/tests/unittests/common/uuidtest.cpp#L161-L168)

I have modified the tests accordingly

**Comment by ubruhin** [comment]
Thank you! :)

**Pull request merged**
