### PR TITLE
Replace GoogleMock directory with a submodule

### PR DESCRIPTION
**Pull request by ubruhin**
Because [GoogleTest and GoogleMock have been moved to GitHub last year](https://groups.google.com/forum/#!topic/googletestframework/UD3nRr3RAQk), and they [released version 1.8.0 two months ago](https://github.com/google/googletest/releases/tag/release-1.8.0), it's a good time to update and replace our [copy of gtest/gmock](https://github.com/LibrePCB/LibrePCB/tree/master/3rdparty/gmock) with a submodule.

I have just forked the [google/googletest](https://github.com/google/googletest) repository into [LibrePCB/googletest](https://github.com/LibrePCB/googletest), where I have created a new branch for our own modifications (basically to add a qmake project file).

Because this would make #127 easier to fix, I think we should merge this PR first.

### CODE REVIEW

**Comment by dns2utf8** [comment]
Maybe add a hint to the readme for interested devs to rerun `git submodule init && git submodule update`?

**Comment by ubruhin** [comment]
> Maybe add a hint to the readme for interested devs to rerun git submodule init && git submodule update?

A permanent hint in the readme which relates only to a specific commit? I wouldn't do that...

**Comment by dns2utf8** [comment]
Yey, true.
Can you automate it in a configure step?

**Comment by ubruhin** [comment]
In my opinion a configure step is not (yet) required. Then developers would need to know that one have to run `./configure` instead of `git submodule init && git submodule update`, so we have not really won something...

At the moment, I would say that developers just need to know that we use submodules. And because all developers are watching this repository, they all got an email with the title of this PR and thus are automatically informed about the new submodule ;)

**Comment by dns2utf8** [comment]
👍 🌈

**Pull request merged**
