### PR TITLE
Fix various translation issues

### PR DESCRIPTION
**Pull request by ubruhin**
Fixing some of the translation issues reported at [Transifex](https://www.transifex.com/librepcb/):
- Fix inconsistent "rescan libraries" menu items
  - Rename "Rescan Library" to "Rescan Libraries"
  - Rename "Update Library Database" to "Rescan Libraries"
  - Use consistent icon and keyboard shortcut
- Stop translating low-level error messages (see [discussion](https://librepcb.discourse.group/t/translation-for-low-level-error-messages/119)).

Open question: Should we stop translating keyboard shortcuts (like "Ctrl+S")? There are a lot of keyboard shortcuts in the translation files, but I'm not sure if that makes sense. Unfortunately I didn't find a good documentation how translation of keyboard shortcuts should be handled...

### CODE REVIEW

**Comment by dbrgn** [comment]
> Should we stop translating keyboard shortcuts (like "Ctrl+S")?

On German keyboards the key is often labelled "Strg" (Steuerung). I'm not sure if there are other languages that also localize that key.

Also, other key like "Space" or "Enter" are also frequently translated.

**Comment by EdizonTN** [comment]
> "Should we stop translating keyboard shortcuts (like "Ctrl+S")?"

I think no. As dbrgn wrote, don't forget for German, and also for non latin languages (Russian, Japanese,...)

**Comment by ubruhin** [comment]
I agree that e.g. "Ctrl" should be translated according the selected language. But currently the "problem" is that the *whole* shortcut (e.g. "Ctrl+S") is going through a translator, and the translated string is then passed to `QKeySequence` - so for example if the translator for some reason translates "Ctrl+S" to "Strg+X", the shortcut is changed to Ctrl+X (at least that's what I expect, but I didn't verify it yet). And if the translation is not understood by `QKeySequence`, the shortcut is probably even broken(?). Therefore IMHO it doesn't make sense to let translators changing the keyboard shortcuts.

But maybe I'm wrong and the translation is only used for displaying the shortcuts in the menu, but not for its functionality - I'll check this. But even in that case there is a risk of inconsistency, since the displayed shortcut might be different from the actually implemented shortcut...

**Comment by EdizonTN** [comment]
Idea:
Exists any easy way how to divide this sequences?
I think, each sequence divide to two parts:
- modifier/s: "CTRL+", "SHIFT+", "ALT+SHIFT+"
- HotKey: "S", "F5", "DEL", "PageUp" - based on content - 1 char length as non-translable (ASCII character), or longer as translable (Fn keys, Cursors keys, ...)

For example: 
"CTLR+S" -> Translated("CTRL+")+Non-translated("S")
"SHIFT+ALT+HOME" -> Translated("SHIFT+ALT+")+Translated("HOME")
"ALT+F12" -> Translated("ALT+")+Translated("F12")
"ALT+2" -> Translated("ALT+")+Non-Translated("2")

**Comment by ubruhin** [comment]
OK now I made some tests and the behavior is (more or less) how I expected it:

- Translators can change keyboard shortcuts (e.g. translating "Ctrl+S" to "F7" will change the shortcut).
- If the translated shortcut not understood by Qt, the shortcut is broken (disappears from the menu) -> this means Qt has to understand *translated* shortcuts in any language, which sounds very weird to me.

But the good thing is: The shortcut displayed in the menus is *not* the string translated by LibrePCB translators, but a string translated by Qt translators. So on a German system "Ctrl+S" appears as "Strg+S" even though LibrePCB translators did not translate the shortcut. Unfortunately currently this doesn't work with our binary releases for Linux (and maybe macOS?) because of https://github.com/probonopd/linuxdeployqt/issues/115, but I'm trying to work around this issue.

So I think we can just disable translation for keyboard shortcuts and everything is fine since the shortcuts will still be displayed in the chosen language -> commit added to disable all shortcut translations.

In addition, I also swapped the terms "trace" and "segment" in the board editor to fix #612.

**Comment by ubruhin** [comment]
> Unfortunately currently this doesn't work with our binary releases for Linux (and maybe macOS?) because of probonopd/linuxdeployqt#115, but I'm trying to work around this issue.

It turned out the problem is not linuxdeployqt, but the fact that Qt translations are simply not installed in our Docker containers used on CI :sob: I'll fix that in a separate PR, so I think this PR is now ready.

**Pull request merged**
