### PR TITLE
Fix catch by value of polymorphic exceptions

### PR DESCRIPTION
**Pull request by rnestler**
Fixes a lot of `warning: catching polymorphic type ‘class
librepcb::Exception’ by value [-Wcatch-value=]` warnings.

### CODE REVIEW

**Comment by ubruhin** [comment]
Looks good :+1:

It seems that this warning was never issued on Travis-CI (otherwise CI would fail because of `-Werror`). @rnestler could you maybe also check if we can enable this warning on CI?

**Comment by rnestler** [comment]
> It seems that this warning was never issued on Travis-CI (otherwise CI would fail because of -Werror). @rnestler could you maybe also check if we can enable this warning on CI?

I suspect it's due to the much older compilers being used for CI. We could just upgrade to a newer compiler though.

**Comment by ubruhin** [comment]
> We could just upgrade to a newer compiler though.

Would you take a look at that? If yes, I'll wait with merging this PR. If not, I'll merge it now.

**Comment by rnestler** [comment]
> Would you take a look at that? If yes, I'll wait with merging this PR. If not, I'll merge it now.

You can merge it now, I can still take a look at it later.

**Comment by ubruhin** [comment]
Thanks!

**Pull request merged**
