### PR TITLE
Alignment: Add basic unit tests

### PR DESCRIPTION
**Pull request by javsanpar**
Tests for "mirrored()" function. 

I want to extend it. ¿Some ideas or other tests files to look for inspiration? :smile:

Related #121

### CODE REVIEW

**Comment by ubruhin** [comment]
Looks very good so far, thanks! :smiley: 

> I want to extend it. ¿Some ideas or other tests files to look for inspiration?

I would say just continue this way by adding tests for the other alignment methods :)

Should we keep this PR open until the alignment tests are complete?

**Comment by javsanpar** [comment]
> Should we keep this PR open until the alignment tests are complete?

Whatever you see more appropriate. I can add more commits to this pull request or create a new pull request with more methods tested.

**Comment by ubruhin** [comment]
OK so then I would prefer to keep this PR open until you consider `AlignmentTest` as complete. Just push more commits to this branch and notify me if I should review it :)

**Comment by javsanpar** [comment]
New commits pushed! What do you think, @ubruhin?

**Comment by ubruhin** [comment]
Cool, looks very good! :+1:

My thoughts:
- In #476 we updated to the latest googletest framework, the macro `INSTANTIATE_TEST_CASE_P()` is now deprecated ans needs to be replaced by `INSTANTIATE_TEST_SUITE_P()` (should fix the CI failure).
- The tests for `mirrored()`, `mirroredH()` and `mirroredV()` could be improved by adding checks that these methods really return a *copy* of the object, without modifying the object itself. Testing such "side effects" makes unit tests especially powerful since this kind of bugs is often hard to find in productive code :slightly_smiling_face:

**Comment by rnestler** [comment]
@ubruhin What is the status on this?

**Comment by javsanpar** [comment]
I just come back of my vacations, so I will work on this again.

> The tests for mirrored(), mirroredH() and mirroredV() could be improved by adding checks that these methods really return a copy of the object, without modifying the object itself. Testing such "side effects" makes unit tests especially powerful since this kind of bugs is often hard to find in productive code 🙂

I still have to do this checks.

**Comment by javsanpar** [comment]
@ubruhin I have been reading the AppVeyor build log and I don't see the cause of the fail. Could you take a look at the log to see if you find something?

Thank you in advance!

**Comment by ubruhin** [comment]
> @ubruhin I have been reading the AppVeyor build log and I don't see the cause of the fail. Could you take a look at the log to see if you find something?

Hmm it looks like a random AppVeyor issue (the build stopped after exactly 1 hour without a visible reason). I restarted the job, hopefully it passes now ;)

**Comment by ubruhin** [comment]
@javsanpar is this PR actually ready? It looks complete and CI succeeded :) It just needs to be rebased to `master` (or `master` merged into this branch), but I could do this by myself.

**Comment by javsanpar** [comment]
> @javsanpar is this PR actually ready? It looks complete and CI succeeded :) 

Yes! Sorry for the poor communication. I suppose you have seen the changes that checks mirrored(), mirroredH() and mirroredV() methods really return a copy of the object.

> It just needs to be rebased to `master` (or `master` merged into this branch), but I could do this by myself.

I just rebased the branch!

Thanks for the help!

**Comment by ubruhin** [comment]
Perfect, thanks for your contribution! :smiley:

**Pull request merged**
