### PR TITLE
Slightly simplify XML files

### PR DESCRIPTION
**Pull request by ubruhin**
- Remove unnecessary xml elements to reduce nesting deepness
- Shorten some xml element tag names and attribute names
- Various other small improvements in xml files

Changes in the workspace are visible at https://github.com/LibrePCB/demo-workspace/commit/779ef9effe11c9bd2e87b08a7ac765d6b5885e22

### CODE REVIEW

**Comment by ubruhin** [comment]
Most of the changes in this PR are improvements for sure. But about one thing I'm not sure if it was an improvement or a worsening:

All library elements had their names, descriptions and keywords defined this way:
```xml
<symbol>
 <!-- ... -->
 <name locale="en_US">IC with 8 Pins</name>
 <name locale="de_DE">IC mit 8 Pins</name>
 <description locale="en_US">description...</description>
 <description locale="de_DE">blabla...</description>
 <keywords locale="en_US">comma,separated,list,of,keywords</keywords>
 <keywords locale="de_DE">komma,separierte,liste</keywords>
 <!-- ... -->
</symbol>
```

But that design to have multiple "lists" (e.g. `name`, `description` and `keywords` lists) in one single xml element (e.g. `symbol`) was only used here, every other list had their own parent xml element. So I decided to use that concept also for names, descriptions and keywords just for consistency. Now it looks like this:

```xml
<symbol>
 <!-- ... -->
 <names>
  <name locale="">IC with 8 Pins</name>
  <name locale="de_DE">IC mit 8 Pins</name>
 </names>
 <descriptions>
  <description locale="">description...</description>
  <description locale="de_DE">blabla...</description>
 </descriptions>
 <keywords>
  <keywords locale="">comma,separated,list,of,keywords</keywords>
  <keywords locale="de_DE">komma,separierte,liste</keywords>
 </keywords>
 <!-- ... -->
</symbol>
```

Now it is consistent with every other list in our XML files, but unfortunately every XML file is now (at least) 6 lines longer. So I wonder if I should revert this to the old concept...

And when using the old concept, why don't do this also for every other list? For example this symbol:

```xml
<symbol>
 <!-- ... -->
 <pins>
  <pin uuid="702df32a-635f-46e9-85d2-5b7e2c20aa87" x="-17.78" y="2.54" length="5.08" rotation="0">1</pin>
  <pin uuid="1339ffc8-afb2-4137-9d37-d9801ac2bfd0" x="-17.78" y="0" length="5.08" rotation="0">2</pin>
  <pin uuid="8207ee9b-89e5-41bc-a633-078952a6c370" x="-17.78" y="-2.54" length="5.08" rotation="0">3</pin>
  <pin uuid="b5ec7a0f-0f26-482e-a68e-e9a8f108cb80" x="-17.78" y="-5.08" length="5.08" rotation="0">4</pin>
  <pin uuid="10f7c99e-9751-409e-aace-d4fa0f21375f" x="17.78" y="-5.08" length="5.08" rotation="180">5</pin>
  <pin uuid="255e12e0-00b7-4563-b82c-42a4899fddf1" x="17.78" y="-2.54" length="5.08" rotation="180">6</pin>
  <pin uuid="b8aa2aa5-9b1b-4d9a-90c5-b584fe48f5a4" x="17.78" y="0" length="5.08" rotation="180">7</pin>
  <pin uuid="db2223ee-84ce-42ef-93b9-ac6a50b07805" x="17.78" y="2.54" length="5.08" rotation="180">8</pin>
 </pins>
 <polygons>
  <polygon layer="10" width="0.254" fill="false" grab_area="true" start_x="-12.7" start_y="-7.62">
   <segment angle="0" end_x="-12.7" end_y="5.08"/>
   <segment angle="0" end_x="12.7" end_y="5.08"/>
   <segment angle="0" end_x="12.7" end_y="-7.62"/>
   <segment angle="0" end_x="-12.7" end_y="-7.62"/>
  </polygon>
 </polygons>
 <ellipses/>
 <texts>
  <text layer="20" v_align="bottom" height="2.54" rotation="0" x="-12.7" y="5.08"  h_align="left">${SYM::NAME}</text>
  <text layer="21" v_align="top" height="2.54" rotation="0" x="-12.7" y="-7.62" h_align="left">${CMP::VALUE}</text>
 </texts>
 <!-- ... -->
</symbol>
```

could be changed to:
```xml
<symbol>
 <!-- ... -->
 <pin uuid="702df32a-635f-46e9-85d2-5b7e2c20aa87" x="-17.78" y="2.54" length="5.08" rotation="0">1</pin>
 <pin uuid="1339ffc8-afb2-4137-9d37-d9801ac2bfd0" x="-17.78" y="0" length="5.08" rotation="0">2</pin>
 <pin uuid="8207ee9b-89e5-41bc-a633-078952a6c370" x="-17.78" y="-2.54" length="5.08" rotation="0">3</pin>
 <pin uuid="b5ec7a0f-0f26-482e-a68e-e9a8f108cb80" x="-17.78" y="-5.08" length="5.08" rotation="0">4</pin>
 <pin uuid="10f7c99e-9751-409e-aace-d4fa0f21375f" x="17.78" y="-5.08" length="5.08" rotation="180">5</pin>
 <pin uuid="255e12e0-00b7-4563-b82c-42a4899fddf1" x="17.78" y="-2.54" length="5.08" rotation="180">6</pin>
 <pin uuid="b8aa2aa5-9b1b-4d9a-90c5-b584fe48f5a4" x="17.78" y="0" length="5.08" rotation="180">7</pin>
 <pin uuid="db2223ee-84ce-42ef-93b9-ac6a50b07805" x="17.78" y="2.54" length="5.08" rotation="180">8</pin>
 <polygon layer="10" width="0.254" fill="false" grab_area="true" start_x="-12.7" start_y="-7.62">
  <segment angle="0" end_x="-12.7" end_y="5.08"/>
  <segment angle="0" end_x="12.7" end_y="5.08"/>
  <segment angle="0" end_x="12.7" end_y="-7.62"/>
  <segment angle="0" end_x="-12.7" end_y="-7.62"/>
 </polygon>
 <text layer="20" v_align="bottom" height="2.54" rotation="0" x="-12.7" y="5.08"  h_align="left">${SYM::NAME}</text>
 <text layer="21" v_align="top" height="2.54" rotation="0" x="-12.7" y="-7.62" h_align="left">${CMP::VALUE}</text>
 <!-- ... -->
</symbol>
```

That would make the XML files even smaller!

What do you think @dbrgn @rnestler?

**Comment by ubruhin** [comment]
> And when using the old concept, why don't do this also for every other list?

I found no real reason to not do this, so I did it and updated this PR accordingly ;)

Changes in the demo workspace when **adding** parent xml nodes to all lists (old idea):
```
4,310 changed files with 118,911 additions and 78,371 deletions
```

**+40'540 lines!**

Changes in the demo workspace when **removing** parent xml nodes from all lists (new idea):
```
4,314 changed files with 340,314 additions and 383,915 deletions
```
**-43'601 lines!** :smiley: 

The diff of the workspace xml files is available here: https://github.com/LibrePCB/demo-workspace/commit/f2efa02430b54e0dbe4cd394d9a791da38064d51

**Comment by rnestler** [comment]
How well does this play together with the eventual switch to S-expressions? For S-Expressions it would probably be nicer to have a member pins which is an array of pin objects isn't it?

**Comment by ubruhin** [comment]
> How well does this play together with the eventual switch to S-expressions?

I think it should be fine as S-expressions are very similar to XML in this particular case.

With parent element:
```lisp
(symbol
 (pins
  (pin (uuid "702df32a-635f-46e9-85d2-5b7e2c20aa87") (x -17.78) (y 2.54) (length 5.08) (rotation 0) (name "1"))
  (pin (uuid "1339ffc8-afb2-4137-9d37-d9801ac2bfd0") (x -17.78) (y 5.08) (length 5.08) (rotation 0) (name "2"))
 )
 (texts
  (text (layer 20) (v_align "bottom") (height 2.54) (rotation 0) (x -12.7) (y 5.08) (h_align "left") (value "${SYM::NAME}"))
  (text (layer 21) (v_align "bottom") (height 2.54) (rotation 0) (x -12.7) (y 2.54) (h_align "left") (value "${SYM::VALUE}"))
 )
)
```

Without parent element:
```lisp
(symbol
 (pin (uuid "702df32a-635f-46e9-85d2-5b7e2c20aa87") (x -17.78) (y 2.54) (length 5.08) (rotation 0) (name "1"))
 (pin (uuid "1339ffc8-afb2-4137-9d37-d9801ac2bfd0") (x -17.78) (y 5.08) (length 5.08) (rotation 0) (name "2"))
 (text (layer 20) (v_align "bottom") (height 2.54) (rotation 0) (x -12.7) (y 5.08) (h_align "left") (value "${SYM::NAME}"))
 (text (layer 21) (v_align "bottom") (height 2.54) (rotation 0) (x -12.7) (y 2.54) (h_align "left") (value "${SYM::VALUE}"))
)
```

Btw, [KiCad also don't use parent elements for lists](https://github.com/KiCad/Connectors.pretty/blob/master/BNC.kicad_mod).

**Comment by dbrgn** [comment]
I think I'd favor the flat layout. The reasoning behind that is that it doesn't really make sense semantically to group all pins in a symbol. Rather, a symbol is a collection of pins, lines, rectangles etc.

In the OOP sense, a symbol would be a `List<Element>`, where `Element` is implemented for all the elements that can occur.

**Comment by ubruhin** [comment]
> I think I'd favor the flat layout.

:+1:

> In the OOP sense, a symbol would be a List<Element>, where Element is implemented for all the elements that can occur.

I think such a design would be too generic, it does not make sense for simple properties like the symbols uuid, version, author and so on. In fact, symbols currently have a `List<Pin>`, `List<Polygon>` and so on because this allows for example to create a `PinListWidget` which takes a `List<Pin>` to make the list editable. This would be more complicated if the list is more generic (requires filters and/or dynamic casts and so on).

But anyway, IMHO one should generally **not** design the file format according to the OOP implementation. The implementation can change at any time while the file format should be as stable as possible.

**Comment by dbrgn** [comment]
@ubruhin I wasn't talking about the implementation, just that conceptually a symbol is a collection of elements, not a collection of pin lists and polygon lists :)

**Comment by ubruhin** [comment]
@dbrgn Ah I see, then I fully agree :smiley:

**Pull request merged**
