### PR TITLE
Library Editor: Rotate pins, pads and texts with right-click

### LINKED ISSUE #290: Library Editor: Rotate pins, pads and texts with right-click
Like in schematic and board editors, the right-click should also rotate items in the symbol editor and package editor, namely:

- Pins and texts in symbol editor
- Pads and texts in package editor

Should be pretty easy to implement because the keyboard shortcut "R" already rotates these items - right-click should just do the same.

Related RFC: https://github.com/LibrePCB/librepcb-rfcs/issues/21

### PR DESCRIPTION
**Pull request by 0xB767B**
Fixes #290

### CODE REVIEW

**Comment by rnestler** [comment]
@0xB767B You committed with an E-Mail address which is not associated with your GitHub account, just so you know. You can either rebase and use `--reset-author` or just add this E-Mail address to your GitHub account.

**Comment by 0xB767B** [comment]
Good point ;-) I'll change it.

**Comment by 0xB767B** [comment]
Changed author information and rebased to master. I guess it's ready to merge now.

**Comment by ubruhin** [comment]
Perfect, thank you! :smiley:

**Pull request merged**
