### PR TITLE
Refactor/cleanup CI configuration and upload artifacts to our own server

### PR DESCRIPTION
**Pull request by ubruhin**
Refactored CI configuration:
- Support "make install" on all platforms -> simplifies packaging also on mac and Windows
- Travis: Also create application bundle (*.dmg) for mac (untested)
- Travis: Refactor helper scripts, make them also working on Windows (in MSYS2 bash)
- AppVeyor: Use MSYS2 bash to run the same helper scripts as on Travis

In addition, I extended our server infrastructure (thanks to [cloudscale.ch](https://www.cloudscale.ch/) for sponsoring the server!). Now we have two new subdomains:
- https://download.librepcb.org/ - Nightly builds are automatically uploaded to this page, so now we have them all at the same place. No more need for BinTray (see also #179) and AppVeyor for file hosting. In future we can also host releases (and maybe more resources) on this page.
- https://doxygen.librepcb.org/ - Doxygen documentation. No more need to host them on GitHub Pages (see also #142).

Both nightly builds and doxygen documentation are now available for all branches! So now we can even download build artifacts or read the documentation from other branches than `master`.

Tasks to do after merging this:
- Delete (or disable) BinTray account https://bintray.com/librepcb
- Delete repository https://github.com/LibrePCB/LibrePCB-Doxygen
- Update installation instructions in https://github.com/LibrePCB/librepcb-doc

### CODE REVIEW

**Comment by ubruhin** [comment]
I can't decide which identifier to use in filenames to specify the architecture :sob: 
- `x86` / `x86_64` (nice because well known)
- `x86` / `x64` (nice because short)
- `i386` / `amd64` (don't like this)
- `32bit` / `64bit` (don't like this)
- ...

**Comment by sebgonzo** [comment]
I vote for `x86` / `x86_64`. It's easier to distinguish than `x86` / `x64` and reffers better to x86 architecture with 64bit extensions.

**Comment by dbrgn** [comment]
Cool!

I agree with @sebgonzo.

Furthermore, a README in the root would be good. What does the `installer_packages` directory mean? What do the three directories inside `nightly_builds` mean?

**Comment by ubruhin** [comment]
OK, let's go with `x86` / `x86_64`.

> Furthermore, a README in the root would be good.

Yeah I can give it a try some time. But generally download.librepcb.org is intended only for file hosting, not for things like installation instructions or something like that.

> What does the installer_packages directory mean?

I'm just experimenting with Qt's installer framework (see #256), where this directory provides packages which will be automatically fetched by the installer.

> What do the three directories inside nightly_builds mean?

They are branch names. Every branch has its own directory here.

**Comment by dbrgn** [comment]
> But generally download.librepcb.org is intended only for file hosting, not for things like installation instructions or something like that.

Yes, but packagers will go to that domain and take a look at what files are available. The information needs to be for them.

**Pull request merged**
