### PR TITLE
Add licensing data for https://reuse.software/

### PR DESCRIPTION
**Pull request by FedericoCeratto**
This could be used to later remove `img/README.md` and simplify license management using `reuse lint` in CI
Please review the licensing data before merging.
The project can then be registered at https://api.reuse.software/register to obtain a badge similar to https://api.reuse.software/info/codeberg.org/FedericoCeratto/rrdnsd

### CODE REVIEW

**Comment by ubruhin** [comment]
I have now removed the `Files: *` entry because it would wrongly apply a license to any file we forgot to list. And now CI fails (of course) because of some icons we don't know the license of:

```
* img/actions/add_component.png
* img/actions/export_gerber.png
* img/actions/export_zip.png
* img/actions/new_folder.png
* img/actions/select.png
* img/library/3d_model.png
* img/library/component.png
* img/library/device.png
* img/places/file.png
* img/places/folder.png
* img/places/folder_open.png
* img/status/info.png
```

So I think we have to replace these icons first before we can get this PR merged.

**Comment by ubruhin** [comment]
@FedericoCeratto I think it makes more sense the other way around, i.e. getting this PR ready first, then updating #1336. This is almost done as I have replaced some icons with unknown license, now only a few ones are left:

```
* img/actions/new_folder.png
* img/actions/select.png
* img/library/3d_model.png
* img/library/device.png
* img/places/folder.png
* img/places/folder_open.png
```

**Comment by ubruhin** [comment]
Found the source of these icons, now all licenses are clarified!

If there are no objections, I'll merge this soon.

**Comment by FedericoCeratto** [comment]
@ubruhin OK!

**Pull request merged**
