### PR TITLE
Fix doxygen build warnings

### PR DESCRIPTION
**Pull request by javsanpar**
Add librepcb namespace to doxygen comments. #43 

Some warnings are already fixed if you want to take a look.

### CODE REVIEW

**Comment by ubruhin** [comment]
Thanks for working on this! :smiley: 

Just one comment so far: It would be great to start all the links with the `#` character, e.g. `#librepcb#AttrTypeString` instead of `librepcb#AttrTypeString`. This helps to avoid broken links if we rename/move/remove classes in future since Doxygen warns about the broken links if the link starts with `#`. So `#librepcb#SomeNonExistentClass` would throw a warning, while `librepcb#SomeNonExistentClass` does not.

You don't have to adjust the already fixed links, but it would be great if you could do it that way from now on :-)

Btw, actually I no longer like the syntax with `#`, actually Doxygen allows to use `::` instead (e.g. `::librepcb::AttrTypeString`), which I like much more since it's C++ style :wink: But no need to change that (now), we could still apply a global search&replace with a regex some time later...

**Comment by javsanpar** [comment]
> Thanks for working on this! smiley

You're welcome.
 
> Just one comment so far: It would be great to start all the links with the `#` character, e.g. `#librepcb#AttrTypeString` instead of `librepcb#AttrTypeString`. This helps to avoid broken links if we rename/move/remove classes in future since Doxygen warns about the broken links if the link starts with `#`. So `#librepcb#SomeNonExistentClass` would throw a warning, while `librepcb#SomeNonExistentClass` does not.
> 
> You don't have to adjust the already fixed links, but it would be great if you could do it that way from now on :-)

I have adjusted the already fixed links :grimacing:. It was easy with this: https://stackoverflow.com/questions/28697799/how-to-search-and-replace-a-string-in-the-lines-added-in-the-last-x-commits

> Btw, actually I don't like the syntax with `#`, actually Doxygen allows to use `::` instead (e.g. `::librepcb::AttrTypeString`), which I like much more since it's C++ style wink But no need to change that (now), we could still apply a global search&replace with a regex some time later...

Okay!

Do you know why UndoCommand appears as "@undocmd" in some files (for example: project.h)?

**Comment by ubruhin** [comment]
> I have adjusted the already fixed links grimacing. It was easy with this: https://stackoverflow.com/questions/28697799/how-to-search-and-replace-a-string-in-the-lines-added-in-the-last-x-commits

Perfect! :smiley:  

> Do you know why UndoCommand appears as "@undocmd" in some files (for example: project.h)?

Yes, `@undocmd` is an alias I have defined here:

https://github.com/LibrePCB/LibrePCB/blob/2e747216114042648c9677d7c18301b793b80918/dev/doxygen/Doxyfile#L211

It is rendered special in the HTML output, but it seems this command is broken too, the namespace for `UndoCommand` is missing ;)

grafik

**Comment by javsanpar** [comment]
> It is rendered special in the HTML output, but it seems this command is broken too, the namespace for `UndoCommand` is missing ;)

Nice, I will fix it!

Also, I have compared the Build Doxygen logs with # (`#librepcd`) and without # (`librepcb`). In the logs with # there are more warnings. Do you know why?

You can take a look on these links:

- With # (`#librepcd`) https://dev.azure.com/LibrePCB/LibrePCB/_build/results?buildId=379&view=logs

- Without # (`librepcb`) https://dev.azure.com/LibrePCB/LibrePCB/_build/results?buildId=371&view=logs

**Comment by ubruhin** [comment]
> Also, I have compared the Build Doxygen logs with # (#librepcd) and without # (librepcb). In the logs with # there are more warnings. Do you know why?

Yes, that's what I tried to explain in my comment above, but I guess it was not clear enough, sorry ;) 

- Without the `#` prefix (e.g. `librepcb#UndoCommand`), Doxygen is lazy - if there exists such a class, it creates a hyperlink to that class. But if such a class does not exist, Doxygen simply ignores it and you will find the raw string `librepcb#UndoCommand` in the HTML output, without hyperlink.
- With the `#` prefix, Doxygen is strict - if the specified class exists, a hyperlink is created. But if it doesn't exist, Doxygen throws a warning in the console output so we can see that our Documentation contains invalid references.

In addition, Doxygen has a configuration key called [`WARN_AS_ERROR`](http://www.doxygen.nl/manual/config.html#cfg_warn_as_error). If we set this to `true`, Doxygen will immediately abort with an error code if there are warnings (like invalid references), and thus our CI would fail too. This makes it much simpler to keep the documentation up to date since we are forced to fix documentation warnings.

Currently we can't enable `WARN_AS_ERROR` because we have a lot of warnings. But once you fixed all warnings, I'd like to enable `WARN_AS_ERROR` since this will lead to a higher quality of our Doxygen documentation.

**Comment by javsanpar** [comment]
Sorry, I didn't get it. I didn't notice there were other namespaces. :sweat_smile:

I have been fixing the hyperlinks, but I am having some difficulties with these links:

https://github.com/LibrePCB/LibrePCB/blob/cefa7e771b238ebcefdf78191274538b92705042/libs/librepcb/workspace/workspace.h#L255
https://github.com/LibrePCB/LibrePCB/blob/dd2dd1bc6366f05940b74843436537df4c8ba2ac/libs/librepcb/common/units/lengthunit.h#L119
https://github.com/LibrePCB/LibrePCB/blob/cefa7e771b238ebcefdf78191274538b92705042/libs/librepcb/common/undostack.h#L199

**Comment by ubruhin** [comment]
Ah, those are broken references to members of the same class. Here the fixes:

- "to lock the version directory (#mVersionPath)" should be changed to "to lock the metadata directory (#mMetadataPath)"
- "Use #toString() and #fromString() instead for this purpose." -> just remove this sentence :-)
- "#isCommandActive()" should be changed to "#isCommandGroupActive()"

**Comment by ubruhin** [comment]
@javsanpar What's actually the state of this?

**Comment by javsanpar** [comment]
Hello, @ubruhin! Sorry for the absence

> @javsanpar What's actually the state of this?

There are several parameters which I changed and need a description:
https://github.com/javsanpar/LibrePCB/blob/ea8b126735f59815df2c707316ffb72ee4e7717e/libs/librepcb/common/attributes/attributesubstitutor.h#L77
https://github.com/javsanpar/LibrePCB/blob/ea8b126735f59815df2c707316ffb72ee4e7717e/libs/librepcb/common/attributes/attributesubstitutor.h#L78
https://github.com/javsanpar/LibrePCB/blob/ea8b126735f59815df2c707316ffb72ee4e7717e/libs/librepcb/project/project.h#L91
https://github.com/javsanpar/LibrePCB/blob/ea8b126735f59815df2c707316ffb72ee4e7717e/libs/librepcb/project/project.h#L92
https://github.com/javsanpar/LibrePCB/blob/ea8b126735f59815df2c707316ffb72ee4e7717e/libs/librepcb/project/project.h#L453
https://github.com/javsanpar/LibrePCB/blob/ea8b126735f59815df2c707316ffb72ee4e7717e/libs/librepcb/project/project.h#L454

They still are warnings in some Markdown files:
image
Do you have any clue on how to fix those warnings?

**Comment by ubruhin** [comment]
Hi @javsanpar,

> Sorry for the absence

No problem :)

>  There are several parameters which I changed and need a description:
>  They still are warnings in some Markdown files:

I could fix them by myself and push a commit to your branch, is this OK for you?

And as explained in https://github.com/LibrePCB/LibrePCB/pull/537#issuecomment-540170170, I'd like to apply a global search&replace to replace `#` by `::`. Then I'd say this branch is ready to merge :)

**Comment by javsanpar** [comment]
> I could fix them by myself and push a commit to your branch, is this OK for you?

Great! No problem.

> And as explained in #537 (comment), I'd like to apply a global search&replace to replace # by ::. Then I'd say this branch is ready to merge :)

Perfect. Anything I can help you with?

**Comment by ubruhin** [comment]
I fixed the remaining warnings and rebased this branch to master. If CI succeeds, I think this is ready to merge.

Thanks for your contribution @javsanpar! :tada:

**Pull request merged**
