### PR TITLE
Allow to modify polygons graphically

### PR DESCRIPTION
**Pull request by ubruhin**
Within the package-, symbol- and board editors, polygons can now be edited graphically:
- Dragging vertices of selected polygons
- Removing vertices by context menu on vertices
- Inserting vertices by context menu of line segments

librepcb_polygons

### CODE REVIEW

**Comment by dbrgn** [comment]
Wohoo, finally! :tada:

**Comment by dbrgn** [comment]
By the way, in many programs a vertex can be added by double-clicking. Maybe that would make sense here as well?

**Comment by ubruhin** [comment]
> By the way, in many programs a vertex can be added by double-clicking. Maybe that would make sense here as well?

A double click on the line currently opens the properties dialog of the polygon, which I consider more important than inserting new vertices. And when double-clicking on a vertex (instead of the line), we don't know whether the new vertex should be inserted *before* or *after* the clicked vertex.

Or how do "many programs" handle this exactly? :)

**Comment by dbrgn** [comment]
Ah, makes sense. Let's keep it like that for consistency!

**Pull request merged**
