### PR TITLE
Document license of icons

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Clarify licensing data for icons.
Unfortunately most files don't have matches.

### CODE REVIEW

**Comment by ubruhin** [comment]
Thanks @FedericoCeratto! :tada: 

The `<` and `>` in the added text (probably) need to be escaped with a leading `\`, currently the rendered view is broken (see [preview](https://github.com/LibrePCB/LibrePCB/blob/d2e073e45e6495dcd8e0b3eb0c40574b06b03b43/img/README.md)).

And to extend the list, the following icons are created by myself:

```
actions/add_hole.png
actions/add_name.png
actions/add_plane.png
actions/add_smt_pad.png
actions/add_symbol_pin.png
actions/add_text.png
actions/add_tht_pad.png
actions/add_value.png
actions/add_via.png
actions/board_editor.png (at least I *guess* I created that one)
actions/draw_line.png
actions/draw_netlabel.png
actions/draw_wire.png
actions/grid.png
actions/hide_planes.png
actions/layers.png
actions/rebuild_plane.png
actions/schematic.png
actions/show_planes.png
command_toolbars/pad_bottom.png
command_toolbars/pad_tht.png
command_toolbars/pad_top.png
command_toolbars/shape_octagon.png
command_toolbars/shape_rect.png
command_toolbars/shape_round.png
command_toolbars/via_octagon.png
command_toolbars/via_round.png
command_toolbars/via_square.png
command_toolbars/wire_45_90.png
command_toolbars/wire_90_45.png
command_toolbars/wire_h_v.png
command_toolbars/wire_straight.png
command_toolbars/wire_v_h.png
empty.png
library/bipolar_capacitor_eu.png
library/bipolar_capacitor_us.png
library/footprint.png
library/gnd.png
library/inductor_eu.png
library/inductor_us.png
library/resistor_eu.png
library/resistor_us.png
library/symbol.png
library/unipolar_capacitor_eu.png
library/unipolar_capacitor_us.png
library/vcc.png
norm/iec_60617.png
norm/ieee_315.png
wizards/watermark.jpg
```

I'd say we can put them under CC0-1.0. They are ugly anyway because my drawing skills are miserable :grin:

The following icons were copied and manually modified:

```
actions/bookmark_gray.png copied from actions/bookmark.png and changed colors
library/package.png copied from library/device.png and modified
places/folder_gray.png copied from places/folder.png and changed colors
places/folder_green.png copied from places/folder.png and changed colors
places/folder_open_gray.png copied from places/folder_open.png and changed colors
places/folder_open_green.png copied from places/folder_open.png and changed colors
places/project_folder.png copied from places/folder.png and modified
```

TODO: Determine the license of the remaining icons:

```
actions/add_component.png
actions/drc.png
actions/export_gerber.png
actions/export_pick_place_file.png
actions/export_zip.png
actions/minus.png
actions/move_to.png
actions/new_file.png
actions/new_folder.png
actions/open_browser.png
actions/ruler.png
actions/select.png
actions/swap.png
actions/undo.png
actions/working.png
app/librepcb.icns
app/librepcb.ico
app/librepcb.png
app/librepcb.svg
command_toolbars/cancel.png
library/3d_model.png
library/component.png
library/device.png
logo/32x32.png
logo/48x48.png
logo/64x64.png
places/file.png
places/folder_open.png
places/folder.png
status/dialog_error.png
status/dialog_warning.png
status/info.png
status/success.png
```

**Comment by ubruhin** [comment]
Thanks @FedericoCeratto! :tada: 

The `<` and `>` in the added text (probably) need to be escaped with a leading `\`, currently the rendered view is broken (see [preview](https://github.com/LibrePCB/LibrePCB/blob/d2e073e45e6495dcd8e0b3eb0c40574b06b03b43/img/README.md)).

And to extend the list, the following icons are created by myself:

```
actions/add_hole.png
actions/add_name.png
actions/add_plane.png
actions/add_smt_pad.png
actions/add_symbol_pin.png
actions/add_text.png
actions/add_tht_pad.png
actions/add_value.png
actions/add_via.png
actions/board_editor.png (at least I *guess* I created that one)
actions/draw_line.png
actions/draw_netlabel.png
actions/draw_wire.png
actions/grid.png
actions/hide_planes.png
actions/layers.png
actions/rebuild_plane.png
actions/schematic.png
actions/show_planes.png
command_toolbars/pad_bottom.png
command_toolbars/pad_tht.png
command_toolbars/pad_top.png
command_toolbars/shape_octagon.png
command_toolbars/shape_rect.png
command_toolbars/shape_round.png
command_toolbars/via_octagon.png
command_toolbars/via_round.png
command_toolbars/via_square.png
command_toolbars/wire_45_90.png
command_toolbars/wire_90_45.png
command_toolbars/wire_h_v.png
command_toolbars/wire_straight.png
command_toolbars/wire_v_h.png
empty.png
library/bipolar_capacitor_eu.png
library/bipolar_capacitor_us.png
library/footprint.png
library/gnd.png
library/inductor_eu.png
library/inductor_us.png
library/resistor_eu.png
library/resistor_us.png
library/symbol.png
library/unipolar_capacitor_eu.png
library/unipolar_capacitor_us.png
library/vcc.png
norm/iec_60617.png
norm/ieee_315.png
wizards/watermark.jpg
```

I'd say we can put them under CC0-1.0. They are ugly anyway because my drawing skills are miserable :grin:

The following icons were copied and manually modified:

```
actions/bookmark_gray.png copied from actions/bookmark.png and changed colors
library/package.png copied from library/device.png and modified
places/folder_gray.png copied from places/folder.png and changed colors
places/folder_green.png copied from places/folder.png and changed colors
places/folder_open_gray.png copied from places/folder_open.png and changed colors
places/folder_open_green.png copied from places/folder_open.png and changed colors
places/project_folder.png copied from places/folder.png and modified
```

TODO: Determine the license of the remaining icons:

```
actions/add_component.png
actions/drc.png
actions/export_gerber.png
actions/export_pick_place_file.png
actions/export_zip.png
actions/minus.png
actions/move_to.png
actions/new_file.png
actions/new_folder.png
actions/open_browser.png
actions/ruler.png
actions/select.png
actions/swap.png
actions/undo.png
actions/working.png
app/librepcb.icns
app/librepcb.ico
app/librepcb.png
app/librepcb.svg
command_toolbars/cancel.png
library/3d_model.png
library/component.png
library/device.png
logo/32x32.png
logo/48x48.png
logo/64x64.png
places/file.png
places/folder_open.png
places/folder.png
status/dialog_error.png
status/dialog_warning.png
status/info.png
status/success.png
```

**Comment by ubruhin** [comment]
These icons are from icons8:

```
actions/drc.png: Color →Programming → Testing→ Pass Fail
actions/export_pick_place_file.png: Office L →Industry → Production Process→ Assembly Line
actions/move_to.png: Color →Ecommerce → Buy and Sell→ Move Stock
actions/ruler.png: Color →Editing → Image Editing→ Ruler
actions/swap.png: Color →Arrows → Actions→ Swap
```

These icons are the LibrePCB logo:

```
app/librepcb.icns
app/librepcb.ico
app/librepcb.png
app/librepcb.svg
logo/32x32.png
logo/48x48.png
logo/64x64.png
```
A 99designs designer created the logo specifically for LibrePCB and we payed money for that. The files in various file formats and sizes are created by myself by converting the source image file. 
If I understand correctly, we can do whatever we want with the logo. But I'm not sure what license makes sense for these files, it should not be allowed to use the LibrePCB logo for things other than LibrePCB. @dbrgn do you have an idea what we should do with these files?

TODO: Remaining icons:

```
actions/add_component.png
actions/export_gerber.png
actions/export_zip.png
actions/minus.png
actions/new_file.png
actions/new_folder.png
actions/open_browser.png
actions/select.png
actions/undo.png
actions/working.png
command_toolbars/cancel.png
library/3d_model.png
library/component.png
library/device.png
places/file.png
places/folder_open.png
places/folder.png
status/dialog_error.png
status/dialog_warning.png
status/info.png
status/success.png
```

**Comment by FedericoCeratto** [comment]
[I'm not a laywer] Logos should be under FLOSS licenses to allow modification and redistribution[1]. If you want to protect the project identity (branding) in terms of its name and logo that should be the purpose of trademark, e.g. [2]. 

[1] https://en.wikipedia.org/wiki/Mozilla_software_rebranded_by_Debian
[2] https://www.debian.org/trademark

**Comment by FedericoCeratto** [comment]
@ubruhin should I rebase the PR? Do you want to merge it now or investigate the license on the remaining files?

**Comment by ubruhin** [comment]
OK, three more licenses found :)

```
actions/working.png icons/png/48x48/symbols/pictograms-road_signs-workman_ahead_roadsign.png PD
command_toolbars/cancel.png icons/png/48x48/actions/dialog-cancel-4.png PD
status/success.png icons/png/48x48/actions/dialog-accept.png PD
```

Remaining icons:

```
actions/add_component.png
actions/export_gerber.png
actions/export_zip.png
actions/minus.png
actions/new_file.png
actions/new_folder.png
actions/open_browser.png
actions/select.png
actions/undo.png
library/3d_model.png
library/component.png
library/device.png
places/file.png
places/folder_open.png
places/folder.png
status/dialog_error.png
status/dialog_warning.png
status/info.png
```

@FedericoCeratto Could you update this branch to include all the icons I listed in my previous comments? And the fix regarding escaping of "<" and ">" characters I mentioned above? Rebasing would be nice, but not required (no conflicts, I could squash-merge).

Afterwards I'd say let's merge this for now. I don't think I can figure out the license of the remaining icons...

**Comment by FedericoCeratto** [comment]
@ubruhin updated

**Comment by ubruhin** [comment]
Thanks @FedericoCeratto! :tada: 

I added two commits to merge the two separate sections of OpenIconLibrary icons and to reorder the sections to have 3rd-party icons at top and self-drawn icons at bottom, I hope that's fine for you as well :slightly_smiling_face: 

Will merge this as soon as CI succeeds.

**Pull request merged**
